= Logstash configs of University API platform

This includes three sets of configs used in the University API and Integration platform setup. One set is for capturing logs from java APIs, the other set is for capturing logs from Kubernetes platform running Mule application, Kafka and Zookeper, and the third set is for shipping logs of Api Gateway - Kong. All sets include filebeat configuration which is used ship log files pre-parsed and pre-tagged to the logstash.

== Java logs

Parses log files in the default SpringBoot format. Additionally, detects if log line contains our custom metrics logs and will parse and tag them accordingly.

== Kubernetes platform logs

Filebeat will ship logs from different locations, tagged by the source:

* Mule application logs
* Kafka logs
* Zookeper logs
* JMX stats of any of these


Additionally, JournalD logs of few core kube services are forwarded to logstash on a separate port. Below is the example of configuring this:

 sudo vi /etc/systemd/system/log-kubelet.service

With the following content

 [Unit]
 Description=JournalD forwarder to Logstash
 After=journald.target
  
 [Service]
 Restart=always
 RestartSec=10s
 ExecStart=/bin/sh -c "/usr/bin/journalctl -o short-iso -S now -f -u kube-proxy -u kubelet | ncat logs-host.its.auckland.ac.nz 7443"
 Type=simple
  
 [Install]
 WantedBy=default.target 

Then start and enable the service

 sudo systemctl daemon-reload
 sudo systemctl enable log-kubelet
 sudo systemctl start log-kubelet
 sudo systemctl status log-kubelet

== Kong logs

Kong is configured to write admin (port 8001) and access (port 8000) logs into separate files. Filebeat will use different *source_type* 
to indicate type of logs. Additionally some of the across-cluster communication is skipped.

Logstash is parsing both logs, extracting first part of url (matches API name in most of the cases). 
A lot of logs are our regular health checks, which logstash will tag accordingly.
